version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.diffplug.spotless
    versions:
    - 5.10.2
    - 5.11.0
    - 5.11.1
    - 5.12.0
    - 5.12.1
  - dependency-name: androidx.activity:activity-compose
    versions:
    - 1.3.0-alpha04
    - 1.3.0-alpha05
    - 1.3.0-alpha06
  - dependency-name: androidx.compose.ui:ui-test-junit4
    versions:
    - 1.0.0-beta02
    - 1.0.0-beta03
    - 1.0.0-beta04
  - dependency-name: androidx.compose.ui:ui-tooling
    versions:
    - 1.0.0-beta02
    - 1.0.0-beta03
    - 1.0.0-beta04
  - dependency-name: androidx.compose.material:material-icons-extended
    versions:
    - 1.0.0-beta02
    - 1.0.0-beta03
    - 1.0.0-beta04
  - dependency-name: androidx.compose.material:material
    versions:
    - 1.0.0-beta02
    - 1.0.0-beta03
    - 1.0.0-beta04
  - dependency-name: androidx.compose.ui:ui
    versions:
    - 1.0.0-beta02
    - 1.0.0-beta03
    - 1.0.0-beta04
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 7.0.0-alpha09
    - 7.0.0-alpha10
    - 7.0.0-alpha11
    - 7.0.0-alpha12
    - 7.0.0-alpha13
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.31
    - 1.4.32
  - dependency-name: dev.chrisbanes.accompanist:accompanist-coil
    versions:
    - 0.6.1
